newProject/myApp/urls.py
from django.contrib import admin
from django.urls import path
from django.views.generic import RedirectView

from . import views

urlpatterns = [    
    #admin and basic urls
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('home/', views.home, name='home'),
    path('about/', views.about, name='about'),
    
    #user acc urls
    path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('user_profile/', views.user_profile, name='user_profile'),
    path('logout/', views.logout, name='logout'),
    
    #product urls
    path('products/', views.products, name='products'),
    path('product_search/', views.product_search, name='product_search'),
    path('cart/', views.cart, name='cart'), 
    path('add_to_cart/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('update_cart/<int:product_id>/', views.update_cart, name='update_cart'),
    path('remove_from_cart/<int:product_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('checkout/', views.checkout, name='checkout'), 
    
    #doctor appointment urls
    path('appointment/', views.appointment, name='appointment'),
    path('doctor_search/', views.doctor_search, name='doctor_search'),
    path('create_appointment/<int:doctor_id>/', views.create_appointment, name='create_appointment'),
    path('cancel_appointment/<int:appointment_id>/<int:doctor_id>/', views.cancel_appointment, name='cancel_appointment'),
    
    #emergency urls not done
    path('emergency/', views.emergency, name='emergency'),
    path('blood_search/', views.blood_search, name='blood_search'),
    
    #error handaling urls
    path('custom_error/', views.custom_error, name='custom_error'),
    path('<path:undefined_path>/', RedirectView.as_view(url='/custom_error/')),
]

newProject/newProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('myApp.urls'))
]

newProject/myApp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.db.models.signals import pre_delete
from django.utils import timezone
    
class UserProfile(models.Model):
    def __str__(self):
        return self.fullname()
    
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    
    def fullname(self):
        return f"{self.user.first_name} {self.user.last_name}"
    
    age = models.IntegerField()
    address = models.CharField(max_length=255)
    mobile = models.CharField(max_length=15)
    GENDER = (
        ('Male', 'Male'),
        ('Female', 'Female'),
    )
    gender = models.CharField(max_length=10, choices=GENDER)
    

@receiver(pre_delete, sender=User)
def delete_user_profile(sender, instance, **kwargs):
    try:
        profile = UserProfile.objects.get(user=instance)
        profile.delete()
    except UserProfile.DoesNotExist:
        pass
    
class MedicalAccessories(models.Model):
    def __str__(self):
        return self.p_name
    
    p_image = models.ImageField()
    p_name = models.CharField(max_length=100)
    p_description = models.CharField(max_length=1000)
    CATEGORY = (
        ('Medicine', 'Medicine'),
        ('Equipment', 'Equipment'),
    )
    p_category = models.CharField(max_length=10, choices=CATEGORY)
    p_cost = models.IntegerField()
    p_count = models.IntegerField()
    v_name = models.CharField(max_length=100)
    v_description = models.CharField(max_length=100)
    

class CartItem(models.Model):
    def __str__(self):
        return self.user.username
    
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    accessory = models.ForeignKey(MedicalAccessories, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    total_cost = models.IntegerField(null = True)
    
class Bill(models.Model):
    def __str__(self):
        return f"{self.customer.username} - {self.created_at}"
    
    customer = models.ForeignKey(User, on_delete=models.CASCADE)
    total_cost = models.DecimalField(max_digits=10, decimal_places=2)
    created_at = models.DateTimeField(default=timezone.now)
    accessories = models.ManyToManyField(MedicalAccessories, through='BillItem')

class BillItem(models.Model):
    bill = models.ForeignKey(Bill, on_delete=models.CASCADE)
    accessory = models.ForeignKey(MedicalAccessories, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    total_cost = models.DecimalField(max_digits=10, decimal_places=2)

class Doctor(models.Model): 
    def __str__(self):
        return self.name
    
    image = models.ImageField()
    name = models.CharField(max_length=255)
    specialty = models.CharField(max_length=255)
    status = models.BooleanField(default=True)
    cost = models.IntegerField()
    available_spots = models.PositiveIntegerField()
    next_available_appointment_date = models.DateField(null=True, blank=True)


class DoctorTimeSlot(models.Model):
    def __str__(self):
        return f"{self.doctor.name} ({self.start_time} - {self.end_time})"
  
    doctor = models.ForeignKey(Doctor, on_delete=models.CASCADE)
    start_time = models.TimeField()
    end_time = models.TimeField()

class Appointment(models.Model):
    def __str__(self):
        return self.user.username
    
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    doctor = models.ForeignKey(Doctor, on_delete=models.CASCADE)
    doctor_time_slot = models.ForeignKey(DoctorTimeSlot, on_delete=models.CASCADE)
    description = models.CharField(max_length=1000)
    appointment_date = models.DateField()
    created_at = models.DateTimeField(auto_now_add=True)
    serial_number = models.PositiveIntegerField(default=0)
    
    
class Hospital(models.Model):
    hospital_name = models.CharField(max_length=100)
    location = models.CharField(max_length=200)
    capacity = models.IntegerField()
    blood_samples = models.ManyToManyField('Blood', related_name='hospitals')

    def __str__(self):
        return self.hospital_name

class Blood(models.Model):
    BLOOD_GROUP_CHOICES = (
        ('A+', 'A+'),
        ('B+', 'B+'),
        ('AB+', 'AB+'),
        ('O+', 'O+'),
        ('A-', 'A-'),
        ('B-', 'B-'),
        ('AB-', 'AB-'),
        ('O-', 'O-'),
    )

    blood_group = models.CharField(max_length=20, choices=BLOOD_GROUP_CHOICES)
    quantity = models.PositiveIntegerField()
    expiry_date = models.DateField()

    def is_available(self):
        return self.quantity > 0

    def __str__(self):
        return f"{self.blood_group}"

newProject/myApp/forms.py
from django import forms
from myApp.models import UserProfile
from django.contrib.auth.models import User
from django_recaptcha.fields import ReCaptchaField

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['age', 'address', 'mobile', 'gender']

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email']

class Captcha(forms.Form):
    captcha = ReCaptchaField()

newProject/myApp/views.py
from django.utils import timezone
from django.urls import reverse
from django.db.models import Prefetch
from .models import *
from django.shortcuts import (
    get_object_or_404, 
    redirect, 
    render
)
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth import (
    authenticate, 
    login as auth_login, 
    logout as auth_logout
)
from .forms import Captcha, UserProfileForm, UserForm
from django.db.models import Q 
from django.shortcuts import render

def custom_error(request,):
    return render(request, 'error.html')

def home(request):
    return render(request, "home.html")

def login(request):
    if request.method == "POST":
        form = Captcha(request.POST)
        if form.is_valid():
            username = request.POST.get("u_name")
            password = request.POST.get("u_password")
            authenticated_user = authenticate(request, username=username, password=password)

            if authenticated_user is not None:
                auth_login(request, authenticated_user)
                messages.success(request, f"Welcome, {username}!")
                return redirect("home")
            else:
                messages.error(request, "Invalid username or password.")
        else:
            messages.error(request, "reCAPTCHA verification failed. Please try again.")

    else:
        form = Captcha()

    return render(request, "login.html", {"form": form})

def register(request):
    if request.method == "POST":
        form = Captcha(request.POST) 

        if form.is_valid():
            u_name = request.POST.get("u_name")
            u_fname = request.POST.get("u_fname")
            u_lname = request.POST.get("u_lname")
            u_email = request.POST.get("u_email")
            u_password = request.POST.get("u_password")
            u_age = request.POST.get("u_age")
            u_address = request.POST.get("u_address")
            u_mobile = request.POST.get("u_mobile")
            u_gender = request.POST.get("u_gender")

            user = User.objects.create_user(username=u_name, first_name=u_fname, last_name=u_lname, email=u_email, password=u_password)
            user.save()
            user_profile = UserProfile(user=user, age=u_age, address=u_address, mobile=u_mobile, gender=u_gender)
            user_profile.save()

            authenticated_user = authenticate(request, username=u_name, password=u_password)

            if authenticated_user is not None:
                auth_login(request, authenticated_user)
                messages.success(request, "Your account has been successfully created.")
                return redirect("home")
            else:
                messages.error(request, "User registration failed. Please try again.")
        else:
            messages.error(request, "reCAPTCHA verification failed. Please try again.")

    else:
        form = Captcha()

    return render(request, "register.html", {"form": form})
from django.db.models import Sum

def user_profile(request):
    user_profile = UserProfile.objects.get(user=request.user)
    profile_form = UserProfileForm(instance=user_profile)
    user_form = UserForm(instance=request.user)
    appointments = Appointment.objects.filter(user=request.user)
    
    # Use a different name for the annotated field, e.g., 'total_item_cost'
    bills = Bill.objects.filter(customer=request.user).prefetch_related(
        Prefetch('billitem_set', queryset=BillItem.objects.select_related('accessory'))
    ).annotate(total_item_cost=Sum('billitem__total_cost'))

    if request.method == "POST":
        if "delete_account" in request.POST:
            request.user.delete()
            auth_logout(request)
            messages.success(request, "Your account has been deleted.")
            return redirect('login')

        profile_form = UserProfileForm(request.POST, instance=user_profile)
        user_form = UserForm(request.POST, instance=request.user)

        if profile_form.is_valid() and user_form.is_valid():
            profile_form.save()
            user_form.save()
            messages.success(request, "Profile updated successfully.")
            return redirect('user_profile')
        else:
            messages.error(request, "Error updating profile. Please check the form.")

    context = {
        'user_profile': user_profile,
        'profile_form': profile_form,
        'user_form': user_form,
        'appointments': appointments,
        'bills': bills,
    }
    return render(request, 'user_profile.html', context)


@login_required
def logout(request):
    user = request.user
    CartItem.objects.filter(user=user).delete()
    
    auth_logout(request)
    messages.success(request, "Logged out Successfully!")
    return redirect('home')

def products(request):
    products = MedicalAccessories.objects.all()

    context = {
        'products': products,
        }

    return render(request, 'products.html', context)

def product_search(request):
    query = request.GET.get('q')
    
    if query:
        products = MedicalAccessories.objects.filter(
            Q(p_name__icontains=query) | Q(p_description__icontains=query)
        )
    else:
        messages.error(request, "Search bar was empty")
        return redirect('products')
    
    if not products:
        messages.error(request, "No product found")
        return redirect('products')

    context = {
        'products': products,
        }

    return render(request, 'products.html', context)

@login_required
def cart(request):
    
    user = request.user
    cart_items = CartItem.objects.filter(user=user)

    for item in cart_items:
        item.total_cost = item.accessory.p_cost * item.quantity
        
        
    total_cost = sum(item.total_cost for item in cart_items)
    
    context = {
        'cart_items': cart_items,
        'total_cost': total_cost
        }
    return render(request, 'cart.html', context)

@login_required
def add_to_cart(request, product_id):

    if request.method == 'POST':
        user = request.user
        product = get_object_or_404(MedicalAccessories, pk=product_id)
        quantity = int(request.POST.get('quantity', 0))

        if quantity <= 0:
            messages.error(request, "Add at least 1 item!")
            return redirect(reverse('products'))
        
        if quantity > product.p_count:
            messages.error(request, "Out of stock!")
            return redirect(reverse('products'))

        cart_item, created = CartItem.objects.get_or_create(user=user, accessory=product)

        if created:
            cart_item.quantity = quantity
        else:
            cart_item.quantity += quantity
            
        cart_item.total_cost = cart_item.quantity * cart_item.accessory.p_cost
        cart_item.save()
        messages.success(request, "Successfully added")
        return redirect(reverse('products'))
    else:
        return redirect('products') 

@login_required
def remove_from_cart(request, product_id):
    
    if request.method == 'POST':
        user = request.user
        product = get_object_or_404(MedicalAccessories, pk=product_id)
        cart_item = CartItem.objects.get(user=user, accessory=product)
        cart_item.delete()
        messages.success(request, "Item removed from your cart.")
    return redirect('cart')

@login_required
def update_cart(request, product_id):
    
    if request.method == 'POST':
        user = request.user
        product = get_object_or_404(MedicalAccessories, pk=product_id)
        quantity = int(request.POST.get('quantity', 1))
        cart_item = CartItem.objects.get(user=user, accessory=product)
        
        if quantity > 0:
            cart_item.quantity = quantity
            cart_item.total_cost = cart_item.quantity * cart_item.accessory.p_cost
            cart_item.save()
            messages.success(request, "Cart item updated.")
        else:
            cart_item.delete()
            messages.success(request, "Item removed from your cart.")
        cart_item = CartItem.objects.get(user=user, accessory=product)
        
    return redirect('cart')

@login_required
def checkout(request):
    user = request.user
    cart_items = CartItem.objects.filter(user=user)

    new_bill = Bill.objects.create(customer=user, total_cost=0, created_at=timezone.now())

    for item in cart_items:
        if item.accessory.p_count >= item.quantity:
            item.accessory.p_count -= item.quantity
            item.accessory.save()
            BillItem.objects.create(
                bill=new_bill,
                accessory=item.accessory,
                quantity=item.quantity,               
                total_cost = item.total_cost
            )

    new_bill.save()
    cart_items.delete()
    messages.success(request, "Checkout successful.")   
    context = {
        'new_bill': new_bill,
    }
    return render(request, 'checkout.html', context)

def appointment(request):
    doctors = Doctor.objects.all()
    context = {
        'doctors': doctors
    }
    return render(request, "appointment.html", context)

def doctor_search(request):
    query_d = request.GET.get('q')
    
    if query_d:
        words = query_d.split()
        name_query = Q()
        specialty_query = Q()
        status_query = Q()

        for word in words:
            if word.lower() == "available":
                status_query = Q(status=True)
                
            elif word.lower() == "unavailable":
                status_query = Q(status=False)
                
            else:
                name_query |= Q(name__icontains=word)
                specialty_query |= Q(specialty__icontains=word)

        doctors = Doctor.objects.filter(name_query | specialty_query, status_query)
    else:
        messages.error(request, "Search bar was empty")
        return redirect('appointment')
        
    if not doctors:
        messages.error(request, "No doctors found.")

newProject/myApp/templates/about.html
{% extends 'base.html' %}
{% load static %}
{% block title %}About Us{% endblock %}

{% block extra-styles %}
<link rel="stylesheet" href="{% static 'css/__about.css' %}">

{% endblock %}

{% block content %}
<div class="about-us">
  <h2>Our Team</h2>
  <div class="team-member">
    <img src="{% static 'image/favicon.png' %}" alt="Team Member 1">
    <h3>Injamul Haque</h3>
    <p>Lead Developer</p>
  </div>
  <div class="team-member">
    <img src="{% static 'image/favicon.png' %}" alt="Team Member 2">
    <h3>Md. Hossain</h3>
    <p>UX Designer</p>
  </div>
  <div class="team-member">
    <img src="{% static 'image/favicon.png' %}" alt="Team Member 3">
    <h3>Shuaib Hossain</h3>
    <p>Marketing Specialist</p>
  </div>

  <div class="project-description">
    <h3>About Us</h3>
    <p>Our E-Seba team is a dedicated and diverse group of experts united by a shared mission: to revolutionize
      healthcare access in Bangladesh. With a range of skills, from development to design and marketing, we've created a
      user-friendly platform that offers convenient, efficient, and transparent healthcare solutions. Our passion drives
      us to serve our community's needs relentlessly.</p>

    <h3>Motivation behind our work</h3>
    <p>Bangladesh, a nation grappling with poverty and an ailing healthcare system, has provided the impetus for our
      endeavor. In critical situations, individuals often face the daunting task of navigating a labyrinth of hospitals,
      leading to prolonged delays. Our solution empowers users with real-time information, enabling them to pinpoint
      nearby ambulances, ascertain ICU availability, and determine blood availability instantly. Furthermore, E-Seba
      addresses fundamental healthcare needs, including medical appointments, acquisition of medical accessories, and
      medication procurement. Our resolve to alleviate the burdens of an inefficient healthcare system has been a
      driving force behind this initiative.</p>

    <h3>Impact on our lives</h3>
    <p>Our initiative, E-Seba, is a catalyst for transformative impact. It champions convenience, offering seamless
      access to medical care and products, particularly benefiting those with mobility constraints and remote residents.
      Through online appointments and prescriptions, we deliver swift, efficient healthcare, reducing waiting times. In
      emergencies, we provide immediate access to critical resources like ambulances, blood donations, and ICUs. Our
      digital record management streamlines patient care while minimizing paperwork. Geographical barriers dissolve,
      ensuring equitable healthcare access for underserved areas. We prioritize health education, empowering individuals
      with vital information. Transparency in transactions and treatment plans builds trust, elevating the healthcare
      experience for all..</p>
  </div>
</div>
{% endblock %}

newProject/myApp/templates/appointment.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Appointment{% endblock %}

{% block extra-styles %}
    <link rel="stylesheet" href="{% static 'css/__appointment.css' %}">
{% endblock %}

{% block content %}
<div class="main-container">
    <div class="search-container">
        <form id="search-form" action="{% url 'doctor_search' %}" method="get">
            <input type="text" id="search-input" name="q" placeholder="Search doctors...">
            <button type="submit" id="search-button">Search</button>
        </form>
    </div>

    <div class="doctor-profile-container">
        {% if doctors %}
            {% for doctor in doctors %}
                <div class="doctor-card">
                    <div class="img1">
                        <img src="{% static 'image/'|add:doctor.image.url %}" alt="Doctor Image" class="product-image">
                    </div>
                    <div class="doctor-info">
                        <h1 class="doctor-name">{{ doctor.name }}</h1>
                        <p class="doctor-specialty">{{ doctor.specialty }}</p>
                        <p class="doctor-cost">Payment: {{ doctor.cost }}</p>
                    </div>
                    <div class="appointment-slots">
                        <div class="appointment-slots">
                            <strong>Patient bookings left: {{doctor.available_spots}}</strong>
                        </div>
                        <h2>Appointment Slots</h2>
                        <ul>
                            {% for slot in doctor.doctortimeslot_set.all %}
                                <li>
                                    <strong>Time:</strong> {{ slot.start_time }} - {{ slot.end_time }}
                                </li>
                            {% endfor %}
                        </ul>
                        
                        {% if not doctor.status %}
                            {% if next_available_slot %}
                                <div class="next-available-slot">
                                    <p><strong>Next Available Slot:</strong> {{ next_available_slot.start_time }} - {{ next_available_slot.end_time }}</p>
                                    <a class="create-appointment-button" href="{% url 'create_appointment' doctor.id %}">Create Appointment</a>
                                </div>
                            {% endif %}
                        {% endif %}
                    </div>
                    <div class="action-buttons">
                        {% if doctor.available_spots > 0 and doctor.status %}
                            <a class="create-appointment-button" href="{% url 'create_appointment' doctor.id %}">Create Appointment</a>
                        {% else %}
                            <span class="unavailable">Unavailable</span>
                            {% if not doctor.status %}
                                <a class="create-appointment-button" style="position:relative; left: -10px; background-color:aqua;" href="{% url 'create_appointment' doctor.id %}">Additional Information</a>
                            {% endif %}
                        {% endif %}
                    </div>
                </div>
            {% endfor %}
        {% endif %}
    </div>
</div>
{% endblock %}

newProject/myApp/templates/cart.html
{% extends 'base.html' %}
{% load static %}

{% block extra-styles %}
<link rel="stylesheet" href="{% static 'css/__cart.css' %}" />
{% endblock %}

{% block title %}Shopping Cart{% endblock %}

{% block content %}
<div class="container">
  
  {% if cart_items %}
  <table class="cart-table">
    <thead>
      <tr>
        <th>Product</th>
        <th>Price</th>
        <th>Quantity</th>
        <th>Total</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      <h1>Your Shopping Cart</h1>
      {% for item in cart_items %}
          <tr>
            <td>{{ item.accessory.p_name }}</td>
            <td>{{ item.accessory.p_cost }} Tk</td>
            <td class="cart-actions">
              <form method="post" action="{% url 'update_cart' item.accessory.id %}">
                {% csrf_token %}
                <input
                  type="number"
                  name="quantity"
                  value="{{ item.quantity }}"
                  min="1"
                />
                <button type="submit" class="update-button">Update</button>
              </form>
            </td>
            <td>{{ item.total_cost }} Tk</td>
            <td class="cart-actions">
              <form method="post" action="{% url 'remove_from_cart' item.accessory.id %}">
                {% csrf_token %}
                <button type="submit" class="remove-button">Remove</button>
              </form>
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>

    <div class="cart-total">
      <strong>Total: {{ total_cost }} Tk</strong>
    </div>

    <div class="checkout-button">
      <a href="{% url 'checkout' %}">Checkout</a>
    </div>
  {% else %}
    <p class="container2">Your shopping cart is empty.</p>
  {% endif %}
</div>
{% endblock %}

newProject/myApp/templates/checkout.html
{% extends 'base.html' %}
{% load static %}

{% block extra-styles %}
<link rel="stylesheet" href="{% static 'css/__checkout.css' %}" />
{% endblock %}

{% block title %}Checkout{% endblock %}

{% block content %}
<div class="container">
    <p>Your shopping cart is empty.</p>
</div>
{% endblock %}

newProject/myApp/templates/create_appointment.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Create appointment{% endblock %}

{% block extra-styles %}
    <link rel="stylesheet" href="{% static 'css/__create_appointment.css' %}">
{% endblock %}

{% block content %}
<div class="main-container">
    <div class="container">
        <h1 style="color: aqua;">Appointment form</h1>
            {% if doctor.next_available_appointment_date %}
                <p style="color: aqua; text-align:center;">You can only choose date's after the doctor is available</p><br>
            {% endif %}
        <h2>Name of the doctor: {{ doctor.name }}</h2>   
        <form method="post" action="">
            {% csrf_token %}
            <input type="hidden" name="doctor_id" value="{{ doctor.id }}">
            {% if doctor.next_available_appointment_date %}
                <p><strong>Doctor is available after:</strong> {{ doctor.next_available_appointment_date }}</p><br>
            {% endif %}

            <div class="form-group">
                <label for="appointment_date">Select Appointment Date:</label>
                <input type="date" id="appointment_date" name="appointment_date" required>
            </div>
            
            <div class="form-group custom-select">
                <label for="appointment_time">Select Appointment Time:</label>
                <select id="appointment_time" name="appointment_time" required>
                    {% for slot in doctor.doctortimeslot_set.all %}
                        <option value="{{ slot.id }}">{{ slot.start_time }} - {{ slot.end_time }}</option>
                    {% endfor %}
                </select>
            </div>
            
            <div class="form-group">
                <label for="description">Disease description:</label>
                <textarea id="description" name="description" rows="7" cols="50" maxlength="1000" required></textarea>
            </div>
        
            <button type="submit" class="btn btn-primary">Register</button>
        </form>
    </div>
</div>

{% endblock %}

newProject/myApp/templates/emergency.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Emergency Services{% endblock %}

{% block extra-styles %}
    <link rel="stylesheet" href="{% static 'css/__emergency.css' %}">
{% endblock %}

{% block content %}
<div class="search-container">
    <form id="search-form" action="{% url 'blood_search' %}" method="get">
        <input type="text" id="search-input" name="q" placeholder="Search blood or hospital...">
        <button type="submit" id="search-button">Search</button>
    </form>
</div>
<div class="main-container">
    {% if hospitals %}
        {% for hospital in hospitals %}
        <div class="container" id="hospital-container">
            <div class="hospital-card">
                <h1 class="hospital-name">{{ hospital.hospital_name }}</h1>
                <p class="hospital-location"><strong>Location:</strong> {{ hospital.location }}</p>
                <p class="hospital-capacity"><strong>Capacity:</strong> {{ hospital.capacity }}</p>
            </div>
            {% if hospital.blood_samples.all %}
                <div class="blood-samples">
                    <h2>Blood Samples</h2>
                    {% for blood_sample in hospital.blood_samples.all %}
                        <div class="blood-sample-card">
                            <h3 class="blood-group">Blood Group: {{ blood_sample.get_blood_group_display }}</h3>
                            <p class="blood-quantity"><strong>Quantity:</strong> {{ blood_sample.quantity }} bag</p>
                            <p class="blood-expiry-date"><strong>Expiry Date:</strong> {{ blood_sample.expiry_date }}</p>
                        </div>
                    {% endfor %}
                </div>
            {% endif %}
        </div>
        {% endfor %}
    {% endif %}
</div>
{% endblock %}

newProject/myApp/templates/error.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="{% static 'image/favicon.png' %}" type="image/x-icon">
    <link rel="stylesheet" href="{% static 'css/__error.css' %}" />
    <title>Error</title>
</head>
<body>
    <div class="error-container">
        {% if user.is_authenticated %}
            <div class="error-message">Oops. The URL is invalid.</div>
            <div class="button-container">
                <a href="{% url 'home' %}" class="button">Home</a>
            </div>
        {% else %}
            <div class="error-message">You need to login to access this feature.</div>
            <div class="button-container">
                <a href="{% url 'home' %}" class="button">Home</a>
                <a href="{% url 'login' %}" class="button">Login</a>
                <a href="{% url 'register' %}" class="button">Register</a>
            </div>  
        {% endif %}
    </div>
</body>
</html>

newProject/myApp/templates/login.html
<!-- login.html -->
{% extends 'base.html' %}
{% load static %}

{% block extra-styles %}
<link rel="stylesheet" href="{% static 'css/__login.css' %}" />
{% endblock %}

{% block title %}Login{% endblock %}

{% block content %}
<div class="container">
    <div class="login-container">
        <h2>Login</h2>
        <form method="post" action="{% url 'login' %}">
            {% csrf_token %}
            <div class="form-group">
                <label for="u_name">Username</label>
                <input type="text" name="u_name" id="u_name" class="form-control" required>
            </div>
            <div class="form-group">
                <label for="u_password">Password</label>
                <input type="password" name="u_password" id="u_password" class="form-control" required>
            </div>
            <div class="captcha_container">
                {{ form.captcha }}
            </div>
            <button type="submit" class="btn-primary">Login</button>
        </form>
    </div>
</div>
{% endblock %}